In [2]:
import numpy as np
from random import randint
scores = [randint(0,100) for i in range(5)]
first_arr =np.array(scores)
print scores
print first_arr
print first_arr.dtype  # .dtype return the data type of the array object

[26, 72, 30, 7, 81]
[26 72 30  7 81]
int64


In [5]:
scores_1 = [[34,56,23,89], [11,45,76,34]]
second_arr = np.array(scores_1)
print second_arr
print second_arr.ndim
print second_arr.shape
print second_arr.dtype 

[[34 56 23 89]
 [11 45 76 34]]
2
(2, 4)
int64


In [7]:
x = np.zeros(10)
print x

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [8]:
np.zeros((4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [11]:
scores = [89,56.34, 76,89, 98]
first_arr =np.array(scores)
print first_arr
print first_arr * first_arr
print first_arr - first_arr
print 1/(first_arr)
print first_arr ** 0.5

[ 89.    56.34  76.    89.    98.  ]
[ 7921.      3174.1956  5776.      7921.      9604.    ]
[ 0.  0.  0.  0.  0.]
[ 0.01123596  0.01774938  0.01315789  0.01123596  0.01020408]
[ 9.43398113  7.5059976   8.71779789  9.43398113  9.89949494]


In [12]:
new_arr = np.arange(12)
print new_arr
print new_arr[5]
print new_arr[4:9]
new_arr[4:9] = 99 #assign sequence of values from 4 to 9 as 99
print new_arr

[ 0  1  2  3  4  5  6  7  8  9 10 11]
5
[4 5 6 7 8]
[ 0  1  2  3 99 99 99 99 99  9 10 11]


In [13]:
modi_arr = new_arr[4:9] 
modi_arr[1] = 123456
print new_arr                  # you can see the changes are refelected in main array. 
modi_arr[:]

[     0      1      2      3     99 123456     99     99     99      9
     10     11]


array([    99, 123456,     99,     99,     99])

In [15]:
matrix_arr =np.array([[3,4,5],[6,7,8],[9,5,1]])
print matrix_arr
print matrix_arr[1]
print matrix_arr[0][2] #first row and third column
print matrix_arr[0,2] # This is same as the above operation

[[3 4 5]
 [6 7 8]
 [9 5 1]]
[6 7 8]
5
5


ValueError: No image data found. Expecting filename, url, or data.

In [16]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print three_d_arr
print "returns the second list inside first list {}".format(three_d_arr[0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
returns the second list inside first list [4 5 6]


In [17]:
three_d_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print three_d_arr[0]

[[1 2 3]
 [4 5 6]]


In [18]:
copied_values = three_d_arr[0].copy() # copy arr[0] value to copied_values
three_d_arr[0]= 99  # change all values of arr[0] to 99 
print "New value of three_d_arr: {}".format(three_d_arr)  # check the new value of three_d_arr 
three_d_arr[0] = copied_values # assign copied values back to three_d_arr[0]
print" three_d_arr again: {}".format(three_d_arr)

New value of three_d_arr: [[[99 99 99]
  [99 99 99]]

 [[ 7  8  9]
  [10 11 12]]]
 three_d_arr again: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
matrix_arr =np.array([[3,4,5],[6,7,8],[9,5,1]])
print "The original matrix {}:".format(matrix_arr)
print "slices the first two rows:{}".format(matrix_arr[:2]) # similar to list slicing. returns first two rows of the array
print "Slices the first two rows and two columns:{}".format(matrix_arr[:2, 1:])
print "returns 6 and 7: {}".format(matrix_arr[1,:2])
print "Returns first column: {}".format(matrix_arr[:,:1]) #Note that a colon by itself means to take the entire axis

The original matrix [[3 4 5]
 [6 7 8]
 [9 5 1]]:
slices the first two rows:[[3 4 5]
 [6 7 8]]
Slices the first two rows and two columns:[[4 5]
 [7 8]]
returns 6 and 7: [6 7]
Returns first column: [[3]
 [6]
 [9]]


In [20]:
personals = np.array(['Manu', 'Jeevan', 'Prakash', 'Manu', 'Prakash', 'Jeevan', 'Prakash'])
print personals == 'Manu' #checks for the string 'Manu' in personals. If present it returns true; else false#

[ True False False  True False False False]


In [21]:
from numpy import random 
random_no = random.randn(7,4)
print random_no
random_no[personals =='Manu'] #The function returns the rows for which the value of manu is true

[[ 1.81490763  0.22377714 -0.06723058  0.00584783]
 [-0.69691577 -0.0971665  -0.82536606 -0.79063476]
 [-0.98968924 -1.62967724  0.69587662  0.01335364]
 [ 0.44401008  0.53047378  0.41794642  0.38001362]
 [ 1.97729371 -0.98068434 -0.35799936  0.04074912]
 [-0.4008847  -0.45061313  0.29929041 -0.8118593 ]
 [ 0.70779163 -1.20457246  0.3741927   0.68185082]]


array([[ 1.81490763,  0.22377714, -0.06723058,  0.00584783],
       [ 0.44401008,  0.53047378,  0.41794642,  0.38001362]])

In [22]:
print personals != 'Manu'


[False  True  True False  True  True  True]


In [24]:
random_no[~(personals == 'Manu')] #get everything except 1st and 4th rows

array([[-0.69691577, -0.0971665 , -0.82536606, -0.79063476],
       [-0.98968924, -1.62967724,  0.69587662,  0.01335364],
       [ 1.97729371, -0.98068434, -0.35799936,  0.04074912],
       [-0.4008847 , -0.45061313,  0.29929041, -0.8118593 ],
       [ 0.70779163, -1.20457246,  0.3741927 ,  0.68185082]])

In [25]:
new_variable = (personals == 'Manu') | (personals == 'Jeevan')
print new_variable
random_no[new_variable] 

[ True  True False  True False  True False]


array([[ 1.81490763,  0.22377714, -0.06723058,  0.00584783],
       [-0.69691577, -0.0971665 , -0.82536606, -0.79063476],
       [ 0.44401008,  0.53047378,  0.41794642,  0.38001362],
       [-0.4008847 , -0.45061313,  0.29929041, -0.8118593 ]])

In [27]:
random_no[random_no < 0] =0 
print random_no

[[ 1.81490763  0.22377714  0.          0.00584783]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.69587662  0.01335364]
 [ 0.44401008  0.53047378  0.41794642  0.38001362]
 [ 1.97729371  0.          0.          0.04074912]
 [ 0.          0.          0.29929041  0.        ]
 [ 0.70779163  0.          0.3741927   0.68185082]]


In [30]:
random_no[ personals != 'Manu'] = 9
print random_no

[[  1.81490763e+00   2.23777138e-01   0.00000000e+00   5.84782845e-03]
 [  9.00000000e+00   9.00000000e+00   9.00000000e+00   9.00000000e+00]
 [  9.00000000e+00   9.00000000e+00   9.00000000e+00   9.00000000e+00]
 [  4.44010083e-01   5.30473779e-01   4.17946423e-01   3.80013622e-01]
 [  9.00000000e+00   9.00000000e+00   9.00000000e+00   9.00000000e+00]
 [  9.00000000e+00   9.00000000e+00   9.00000000e+00   9.00000000e+00]
 [  9.00000000e+00   9.00000000e+00   9.00000000e+00   9.00000000e+00]]


In [33]:
from numpy import random
algebra = random.randn(7,4) 
for j in range(7):
    algebra[j] = j
algebra

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.]])

In [35]:
algebra[[4,5,1]]

array([[ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 1.,  1.,  1.,  1.]])

In [36]:
fancy = np.arange(36).reshape(9,4)
print fancy
fancy[[1,4,3,2],[3,2,1,0]] #the position of the output array are[(1,3),(4,2),(3,1),(2,0)]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


array([ 7, 18, 13,  8])

In [39]:
fancy[[1, 4, 8, 2]][[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [32, 33, 34, 35]])

In [40]:
fancy[np.ix_([1,4,8,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

In [44]:
transpose= np.arange(12).reshape(3,4) 
transpose.T
np.dot(transpose.T, transpose)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [45]:
funky =np.arange(8)
print np.sqrt(funky)
print np.exp(funky) #exponent of the array

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03]


In [47]:
x = random.randn(10)
y = random.randn(10)
print x
print y
print np.maximum(x,y)
print np.modf(x)# function modf returns the fractional and integral parts of a floating point arrays

[ 0.68457099  0.60358284  1.39687538 -2.09292923  1.4933661  -1.38060413
 -0.68267713  0.31641464  0.45950486  0.84211897]
[-0.91287744  0.89039397  0.18752632  0.27359565 -0.5357902  -0.59478922
  0.49719848 -0.54742504  0.34082622  0.43973132]
[ 0.68457099  0.89039397  1.39687538  0.27359565  1.4933661  -0.59478922
  0.49719848  0.31641464  0.45950486  0.84211897]
(array([ 0.68457099,  0.60358284,  0.39687538, -0.09292923,  0.4933661 ,
       -0.38060413, -0.68267713,  0.31641464,  0.45950486,  0.84211897]), array([ 0.,  0.,  1., -2.,  1., -1., -0.,  0.,  0.,  0.]))


In [49]:
x = random.randn(10)
print x
print np.rint(x)

[-1.09800475 -0.08215504  0.69162893 -1.06094834 -0.30079081  0.78841491
 -1.46474702  0.35139972  1.37696094  0.23914196]
[-1. -0.  1. -1. -0.  1. -1.  0.  1.  0.]


In [52]:
mtrices =np.arange(-5,5,1)
x, y = np.meshgrid(mtrices, mtrices)
print "Matrix values of y: {}".format(y)
print "Matrix values of x: {}".format(x)

Matrix values of y: [[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4]]
Matrix values of x: [[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]]


In [59]:
jp =np.arange(12).reshape(4,3)
print"The arrays are: {}".format(jp)
print "The sum of rows are :{}".format(np.sum(jp, axis =1)) #axis =0, gives you sum of the columns. axis =1 , gives sum of rows.
print jp.cumsum(0)
print jp.cunprod(0)

The arrays are: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The sum of rows are :[ 3 12 21 30]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]
[[  0   1   2]
 [  0   4  10]
 [  0  28  80]
 [  0 280 880]]


In [60]:
xp =np.random.randn(100)
print(xp > 0).sum() # sum of all positive values
print (xp < 0).sum()
tandf =np.array([True,False,True,False,True,False])
print tandf.any()#checks if any of the values are true
print tandf.all() #returns false even if a single value is false
#These methods also work with non-boolean arrays, where non-zero elements evaluate to True.

58
42
True
False


In [61]:
lp = np.random.randn(8)
print lp
lp.sort()
lp

[ 0.22172194 -0.20580872  0.1387947  -0.82035609  0.21593106 -1.19460804
 -1.12843379  1.07096924]


array([-1.19460804, -1.12843379, -0.82035609, -0.20580872,  0.1387947 ,
        0.21593106,  0.22172194,  1.07096924])

In [71]:
tp = np.random.randn(4,4)
tp

array([[-0.45758293,  0.03882865,  0.08150508, -0.29173859],
       [ 0.74273552,  1.43625665,  0.25025752, -0.2093197 ],
       [-0.45186344,  0.58137578, -0.28536481,  1.4518138 ],
       [ 0.35058055, -0.76475455,  0.19679268,  0.15495939]])

In [74]:
tp.sort(0)
print tp
tp.sort(1)
print tp

[[-0.45758293 -0.76475455 -0.28536481 -0.29173859]
 [-0.45186344  0.03882865  0.08150508 -0.2093197 ]
 [ 0.35058055  0.58137578  0.19679268  0.15495939]
 [ 0.74273552  1.43625665  0.25025752  1.4518138 ]]
[[-0.76475455 -0.45758293 -0.29173859 -0.28536481]
 [-0.45186344 -0.2093197   0.03882865  0.08150508]
 [ 0.15495939  0.19679268  0.35058055  0.58137578]
 [ 0.25025752  0.74273552  1.43625665  1.4518138 ]]


In [75]:
personals = np.array(['Manu', 'Jeevan', 'Prakash', 'Manu', 'Prakash', 'Jeevan', 'Prakash'])
np.unique(personals)# returns the unique elements in the array

array(['Jeevan', 'Manu', 'Prakash'], 
      dtype='|S7')

In [76]:
set(personals) # set is an alternative to unique function

{'Jeevan', 'Manu', 'Prakash'}

In [77]:
np.in1d(personals, ['Manu']) #in1d function checks for the value 'Manu' and returns True, other wise returns False

array([ True, False, False,  True, False, False, False], dtype=bool)

In [82]:
cp = np.array([[1,2,3],[4,5,6]])
dp = np.array([[7,8],[9,10],[11,12]])
cp.dot(dp) # this is equivalent to np.dot(x,y)
print np.ones(3)

[ 1.  1.  1.]


In [85]:
from numpy.linalg import inv, qr
cp = np.array([[1,2,3],[4,5,6]])
new_mat = cp.T.dot(cp) # multiply cp inverse and cp, this is element wise multiplication
print new_mat

sp = np.random.randn(5,5)
print inv(sp)
rt = inv(sp)
print rt

[[17 22 27]
 [22 29 36]
 [27 36 45]]
[[ -1.74995136e-01   1.08271241e+00   1.10377879e+00  -6.73516851e-01
    7.92582356e-01]
 [  7.78563059e-01  -6.29026388e-01  -1.98658728e+00   1.13555710e+00
   -7.72170194e-01]
 [  2.35529187e-01  -1.09400406e-01  -5.32122149e-01   7.72733178e-01
   -4.11474845e-01]
 [  4.47494332e-02   7.74705478e-01   8.67692485e-01  -4.70420860e-01
    7.81666510e-02]
 [  1.69385473e-03  -8.40947680e-02   3.85461605e-01  -8.16997322e-02
    2.28773940e-01]]
[[ -1.74995136e-01   1.08271241e+00   1.10377879e+00  -6.73516851e-01
    7.92582356e-01]
 [  7.78563059e-01  -6.29026388e-01  -1.98658728e+00   1.13555710e+00
   -7.72170194e-01]
 [  2.35529187e-01  -1.09400406e-01  -5.32122149e-01   7.72733178e-01
   -4.11474845e-01]
 [  4.47494332e-02   7.74705478e-01   8.67692485e-01  -4.70420860e-01
    7.81666510e-02]
 [  1.69385473e-03  -8.40947680e-02   3.85461605e-01  -8.16997322e-02
    2.28773940e-01]]


In [88]:
sp = np.random.randn(5,5)
print inv(sp)
rt = inv(sp)
print rt
print sp.dot(rt)

[[-1.42498553 -0.57626931 -0.86854344 -0.86983557 -0.07450531]
 [-1.55769912 -0.50279078 -1.0570108  -1.55320343 -0.09275452]
 [-0.00385811  0.29098167 -0.22843454  0.14364882 -0.05581856]
 [-1.09288693 -0.56330837 -0.60578968 -0.94066232 -0.46542534]
 [-0.89236915 -0.55016866 -1.00739761 -0.52935065 -0.01552893]]
[[-1.42498553 -0.57626931 -0.86854344 -0.86983557 -0.07450531]
 [-1.55769912 -0.50279078 -1.0570108  -1.55320343 -0.09275452]
 [-0.00385811  0.29098167 -0.22843454  0.14364882 -0.05581856]
 [-1.09288693 -0.56330837 -0.60578968 -0.94066232 -0.46542534]
 [-0.89236915 -0.55016866 -1.00739761 -0.52935065 -0.01552893]]
[[  1.00000000e+00  -2.22044605e-16  -2.22044605e-16  -3.33066907e-16
   -3.12250226e-17]
 [  0.00000000e+00   1.00000000e+00  -2.22044605e-16   1.11022302e-16
    3.46944695e-17]
 [ -2.22044605e-16   2.22044605e-16   1.00000000e+00   0.00000000e+00
   -1.38777878e-17]
 [ -7.21644966e-16   2.74086309e-16   1.83880688e-16   1.00000000e+00
    2.38524478e-18]
 [ -4.16

In [89]:
q,r = qr(sp)
print q
r

[[-0.76020221  0.05255815 -0.1350297  -0.26173993 -0.57670568]
 [ 0.10068992 -0.48325845  0.79351478 -0.0154426  -0.35555396]
 [ 0.37178788 -0.08656469 -0.38122086  0.53394026 -0.65104438]
 [ 0.46214707  0.59695213  0.1410846  -0.54141567 -0.34210004]
 [ 0.2452509  -0.63233979 -0.43228122 -0.59416379 -0.01003578]]


array([[ 3.54516586, -1.11294375,  0.34528631, -0.85323602, -1.82303253],
       [ 0.        , -1.62356692,  0.157844  ,  1.63760333,  0.76890417],
       [ 0.        ,  0.        ,  2.75558625,  0.61894996, -0.61862735],
       [ 0.        ,  0.        ,  0.        ,  1.32078797, -1.32426359],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.64626357]])